# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90167f97db9e540dcafff9514a0cb7289318d00e19e322c3182533cbcc08185a59c32d4c9040ae8151b752cca5759877a2b9eba5e30b940de80f04f1774ae8c5

test:
  secret_key_base: 1577cb2760da08d0db5630c88e9b2fbf96e9c69146c1a2a614a1eb9bd1cb65a90b5c718656de50711948ccb2fa0dea4c0639fd26ccfd3dcf1c59c6f13e0f57a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
